=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

first = 0
second = 1
i = 0
sum = 0
sum2 = 0

while i <= 4000000

  i = first + second


  if first + second  >= 4000000
    puts "terminating program "
    puts " first = #{first}"
    puts " second = #{second}"
    puts " sum = #{sum}"
    puts " sum2 = #{sum2}"
    puts " value of i = #{i}"
    puts ""
    break
  end

  sum2 += i if i % 2 == 0
  if sum2 >= 4000000
    puts "terminating program here "
    puts " first = #{first}"
    puts " second = #{second}"
    puts " sum = #{sum}"
    puts " sum2 = #{sum2}"
    puts " value of i = #{i}"
    puts ""
    break

  end
  sum += i if i % 2 == 0
  if i % 2 == 0
  puts "true, value of i = #{i}"
  puts ""
  end



  first = second
  second = i


  puts " first = #{first}"
  puts " second = #{second}"
  puts " sum = #{sum}"
  puts " sum2 = #{sum2}"
  puts " value of i = #{i}"
  puts ""

end
puts i